movies_data = [
    {
        "id": 1,
        "name": "Dangal",
        "genre": "Biographical Sports Drama (Indian)",
        "releaseYear": 2016,
        "rating": "8.3/10",
        "duration": "2h 41m",
        "director": "Nitesh Tiwari",
        "cast": "Aamir Khan, Fatima Sana Shaikh, Sanya Malhotra",
        "description": "Former wrestler Mahavir Singh Phogat trains his daughters to become world champions.",
        "bannerUrl": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQMCj20Dhxm40PDsgiS1lMZaNj8lepMfMv9zn3LsbwLWu2ovzUk",
        "trailer": "https://www.youtube.com/embed/x_7YlGv9u1g"
    },
    {
        "id": 2,
        "name": "Baahubali 2",
        "genre": "Epic Action (Indian)",
        "releaseYear": 2017,
        "rating": "8.2/10",
        "duration": "2h 47m",
        "director": "S.S. Rajamouli",
        "cast": "Prabhas, Rana Daggubati, Anushka Shetty",
        "description": "Amarendra Baahubali, the heir apparent to the throne of Mahishmati, finds his life and relationships endangered as his adoptive brother Bhallaladeva conspires to claim the throne.",
        "bannerUrl": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTnMA16Y55ki6WxoLTdTmxNnKwYCZiNwi0DvCakttCRBQgZyJpJ",
        "trailer": "https://www.youtube.com/embed/G62HrubdD6o"
    },
    {
        "id": 3,
        "name": "RRR",
        "genre": "Action Drama (Indian)",
        "releaseYear": 2022,
        "rating": "7.8/10",
        "duration": "3h 2m",
        "director": "S.S. Rajamouli",
        "cast": "N.T. Rama Rao Jr., Ram Charan, Alia Bhatt",
        "description": "A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.",
        "bannerUrl": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRx0wTDoneV8OuMM6hNfD7vfibB_jt6FcCL-u8H2DljlRXgGCoG",
        "trailer": "https://www.youtube.com/embed/NgBoKQy3RGU"
    },
    {
        "id": 4,
        "name": "K.G.F.: Chapter 2",
        "genre": "Action Thriller (Indian)",
        "releaseYear": 2022,
        "rating": "8.3/10",
        "duration": "2h 48m",
        "director": "Prashanth Neel",
        "cast": "Yash, Sanjay Dutt, Raveena Tandon",
        "description": "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes. While his allies look up to him, the government sees him as a threat to law and order.",
        "bannerUrl": "https://m.media-amazon.com/images/M/MV5BZmQzZjVkZTUtYjI4ZC00ZDJmLWI0ZDUtZTFmMGM1Mzc5ZjIyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
        "trailer": "https://www.youtube.com/embed/Qah9sSIXJqk"
    },
    {
        "id": 5,
        "name": "Jawan",
        "genre": "Action Thriller (Indian)",
        "releaseYear": 2023,
        "rating": "7.0/10",
        "duration": "2h 49m",
        "director": "Atlee",
        "cast": "Shah Rukh Khan, Nayanthara, Vijay Sethupathi",
        "description": "A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.",
        "bannerUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA8fxJgOk6Q4UGjmsa1q3CQ1Q05Lt0Dn1leAl6_KexCEjqJAe6",
        "trailer": "https://www.youtube.com/embed/MWOtxug9vTg"
    },
    {
        "id": 6,
        "name": "Pathaan",
        "genre": "Action Thriller (Indian)",
        "releaseYear": 2023,
        "rating": "5.9/10",
        "duration": "2h 26m",
        "director": "Siddharth Anand",
        "cast": "Shah Rukh Khan, Deepika Padukone, John Abraham",
        "description": "An Indian spy takes on the leader of a group of mercenaries who have nefarious plans to target his homeland.",
        "bannerUrl": "https://m.media-amazon.com/images/M/MV5BNDdkNTY1MDQtY2I5MC00OTFlLTg5OWQtZWE2YzE5NWFiMDgzXkEyXkFqcGc@._V1_.jpg",
        "trailer": "https://www.youtube.com/embed/vqu4z34wENw"
    },
    {
        "id": 7,
        "name": "Bajrangi Bhaijaan",
        "genre": "Drama (Indian)",
        "releaseYear": 2015,
        "rating": "8.1/10",
        "duration": "2h 43m",
        "director": "Kabir Khan",
        "cast": "Salman Khan, Harshaali Malhotra, Nawazuddin Siddiqui",
        "description": "An Indian man with a magnanimous heart takes a young mute Pakistani girl back to her homeland to reunite her with her family.",
        "bannerUrl": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQRGNMHX7ZlA7yp_XDkjD1iBMeFJnSkBM3PKju8auM_SpKFP4Dm",
        "trailer": "https://www.youtube.com/embed/vyX4toD395U"
    },
    {
        "id": 8,
        "name": "3 Idiots",
        "genre": "Comedy Drama (Indian)",
        "releaseYear": 2009,
        "rating": "8.4/10",
        "duration": "2h 50m",
        "director": "Rajkumar Hirani",
        "cast": "Aamir Khan, Madhavan, Sharman Joshi",
        "description": "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.",
        "bannerUrl": "https://upload.wikimedia.org/wikipedia/en/thumb/d/df/3_idiots_poster.jpg/250px-3_idiots_poster.jpg",
        "trailer": "https://www.youtube.com/embed/K0eDlFX9GZ8"
    },
    {
        "id": 9,
        "name": "PK",
        "genre": "Satirical Comedy (Indian)",
        "releaseYear": 2014,
        "rating": "8.1/10",
        "duration": "2h 33m",
        "director": "Rajkumar Hirani",
        "cast": "Aamir Khan, Anushka Sharma, Sanjay Dutt",
        "description": "An alien on Earth loses the only device he can use to communicate with his spaceship. His innocent nature and child-like questions force the country to evaluate the impact of religion on its people.",
        "bannerUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT2FV_zTaMbFBBdsf_-RfdWTf7ES38QXjIiGLbzpYNjS5GRk2Sf",
        "trailer": "https://www.youtube.com/embed/SOXWc32k4zA"
    },
    {
        "id": 10,
        "name": "Sholay",
        "genre": "Action Adventure (Indian)",
        "releaseYear": 1975,
        "rating": "8.1/10",
        "duration": "3h 24m",
        "director": "Ramesh Sippy",
        "cast": "Dharmendra, Amitabh Bachchan, Sanjeev Kumar",
        "description": "After his family is murdered by a notorious and ruthless bandit, a former police officer enlists the services of two outlaws to capture him.",
        "bannerUrl": "https://m.media-amazon.com/images/M/MV5BOGQ2NjU0MjktMTUyYi00NjQwLTg0ZTAtNzg5NTk0YTRlMWNhXkEyXkFqcGc@._V1_.jpg",
        "trailer": "https://www.youtube.com/embed/hB835H_rK0g",
        "director": "James Cameron",
        "cast": "Leonardo DiCaprio, Kate Winslet, Billy Zane",
        "description": "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.",
        "bannerUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRwQlOeIost26Qv6cAAT73c9LLi0oRcXOJ6QQ5h3J1fUogSX_sD",
        "trailer": "https://www.youtube.com/embed/CHekzSiZcw4"
    },
    {
        "id": 23,
        "name": "Star Wars",
        "genre": "Science Fiction (Hollywood)",
        "releaseYear": 2015,
        "rating": "7.8/10",
        "duration": "2h 18m",
        "director": "J.J. Abrams",
        "cast": "Daisy Ridley, John Boyega, Oscar Isaac",
        "description": "As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.",
        "bannerUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTITEc_k9echyKt6RJbPKiY-lS4RqCh2NWkAsrvI37wKFjG1po5",
        "trailer": "https://www.youtube.com/embed/sGbxmsDFVnE"
    },
    {
        "id": 24,
        "name": "Inception",
        "genre": "Science Fiction Thriller (Hollywood)",
        "releaseYear": 2010,
        "rating": "8.8/10",
        "duration": "2h 28m",
        "director": "Christopher Nolan",
        "cast": "Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page",
        "description": "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
        "bannerUrl": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQovCe0H45fWwAtV31ajOdXRPTxSsMQgPIQ3lcZX_mAW0jXV3kH",
        "trailer": "https://www.youtube.com/embed/YoHD9XEInc0"
    },
    {
        "id": 25,
        "name": "The Dark Knight",
        "genre": "Superhero Action (Hollywood)",
        "releaseYear": 2008,
        "rating": "9.0/10",
        "duration": "2h 32m",
        "director": "Christopher Nolan",
        "cast": "Christian Bale, Heath Ledger, Aaron Eckhart",
        "description": "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
        "bannerUrl": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQkUywIUXDjHSQJIaNHYVs08osgBpF5Ot-xmB_omyEZeeRP9Xug",
        "trailer": "https://www.youtube.com/embed/EXeTwQWrcwY"
    },
    {
        "id": 26,
        "name": "Pulp Fiction",
        "genre": "Crime Drama (Hollywood)",
        "releaseYear": 1994,
        "rating": "8.9/10",
        "duration": "2h 34m",
        "director": "Quentin Tarantino",
        "cast": "John Travolta, Uma Thurman, Samuel L. Jackson",
        "description": "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
        "bannerUrl": "https://m.media-amazon.com/images/I/914mMOJHWVL._UF894,1000_QL80_.jpg",
        "trailer": "https://www.youtube.com/embed/s7EdQ4FqbhY"
    },
    {
        "id": 27,
        "name": "Shawshank Redemption",
        "genre": "Drama (Hollywood)",
        "releaseYear": 1994,
        "rating": "9.3/10",
        "duration": "2h 22m",
        "director": "Frank Darabont",
        "cast": "Tim Robbins, Morgan Freeman, Bob Gunton",
        "description": "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
        "bannerUrl": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRipfEoI8fb4qxidki3e_kp3fr_Kopvoi2yCKcpJGf2ngnKweMR",
        "trailer": "https://www.youtube.com/embed/6hB3S9bIaco"
    },
    {
        "id": 28,
        "name": "The Godfather",
        "genre": "Crime Drama (Hollywood)",
        "releaseYear": 1972,
        "rating": "9.2/10",
        "duration": "2h 55m",
        "director": "Francis Ford Coppola",
        "cast": "Marlson Brando, Al Pacino, James Caan",
        "description": "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
        "bannerUrl": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTWmKJlXjXTiE9hkekFBy9WCRMf0eKZx2mrsgenlO-qzr9H7v0A",
        "trailer": "https://www.youtube.com/embed/sY1S34973zA"
    },
    {
        "id": 29,
        "name": "Spider-Man",
        "genre": "Superhero Action (Hollywood)",
        "releaseYear": 2021,
        "rating": "8.2/10",
        "duration": "2h 28m",
        "director": "Jon Watts",
        "cast": "Tom Holland, Zendaya, Benedict Cumberbatch",
        "description": "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear.",
        "bannerUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtauzk4w5HwCXrx3nAm5VTFcywz62gV18C3A7KFT03SgB2k8c0",
        "trailer": "https://www.youtube.com/embed/JfVOs4VSpmA"
    },
    {
        "id": 30,
        "name": "Dune: Part Two",
        "genre": "Science Fiction (Hollywood)",
        "releaseYear": 2024,
        "rating": "8.6/10",
        "duration": "2h 46m",
        "director": "Denis Villeneuve",
        "cast": "Timothée Chalamet, Zendaya, Rebecca Ferguson",
        "description": "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
        "bannerUrl": "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRBu8Gzdygf5OOqBJUIJ3-ZxiPbLh62OhvLmtOvuR7x2gF3DucU",
        "trailer": "https://www.youtube.com/embed/Way9Dexny3w"
    }
]   
    